### ISSUE TITLE
Empty reading when endpoint is down. Should be nil value.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-modbus-ip-plugin#54]
We used to give nil reading values when we were not able to successfully read a device. Now the device read gives an empty result set and the read all endpoint just omits the reading.

VSM controller is down. Query Service Entrance Door Switch
```
ubuntu@w1:~/src/vem-access/burnin/site_tests$ curl http://${SYNSE_IP}:5000/v3/read/1b679647-c421-5c35-a38b-3eb71b43bf2f
[

]
```

We should get something like this:
```
[
  {
    "device": "1b679647-c421-5c35-a38b-3eb71b43bf2f",
    "timestamp": "2020-05-11T22:30:13Z",
    "type": "status",
    "device_type": "status",
    "unit": null,
    "value": null,
    "context": {
      "model": "Vapor VSM"
    }
  }
]
```

**Comment by edaniszewski** [comment]
Good catch.

I think this brings up a potential need for a larger discussion of the implications/uses of `nil` as reading values. I was thinking about this a bit last night. Our current stance is that we can have nil readings which signify no data / not being  able to successfully read. I don't know that the behavior is well-documented, but it should be. I think thats generally fine as it means  that someone can filter readings for nil and then do what they want (discard, log, do something else, ...) - but at least they know that the reads  were attempted. The other approach which I think prometheus takes is to just not provide a reading (like the behavior described here). I think in  theory thats a nice approach (no data, no reading), but in practice it feels harder to handle in some ways.

Where our current `nil`-means-no-reading approach feels a bit less defined is in cases were maybe someone wants  to  return `nil` as a valid reading value (I don't have an example, so this is mostly hypothetical). Additionally around the distinction between error handling and just no reading (e.g. error happened, so return nil vs tried reading from the device but there is no  current reading for it). I don't think these are necessarily particularly difficult to answer, but I just don't think they've been answered and documented fully, so we may want to discuss at some point.

Didn't mean to derail this.. just wanted to jot down my thoughts somewhere sorta relevant.

**Comment by edaniszewski** [comment]
Also, @MatthewHink if you're working on fixing this, let me know. Otherwise, you can assign me to it and I can throw together a fix sometime today.

**Comment by edaniszewski** [comment]
This isn't entirely as easy as I thought it could be once I've started looking into it, at least not to enforce globally for all plugins.

At an individual plugin level, we can just create an empty reading and pass it up. At the SDK level though,  when a read returns an error, the SDK doesn't have enough information to make an empty reading(s) for that device, since its entirely up to the implementation of the handler for what output is used, how many readings can be produced, etc -- this info is not available to the SDK as a whole.

So while we can add in handling in this plugin to return a nil reading when the `failOnError` option is set to false, when there is an error that we do capture, that will result in the behavior where it propagates up to the SDK and we are unable to make a reading, so there will still be a  no-reading-on-error behavior.
